### ISSUE TITLE
Missing Text and unable to download certain comics.

### ISSUE THREAD

**Issue by aDragon** [rogrmil/WSDC#1]
Certain Stories for the RA comic are incomplete.
https://imgur.com/hKt8IG9
I also am unable to download certain other comics as the download bar is grayed out for them even though I have not downloaded them previously.

**Comment by rogrmil** [comment]
Try it with the new version. It has a better space allocation system for that sort of thing

**Comment by aDragon** [comment]
Unfortunatley it still seems to occur.
So far (With what I have read of RA) it has occured on comics number: 13, 14, 15, 16, 19, 22, 25, 28, 29, 32, 33, 45, 51, 53, 55, 61, 76, 77, 80, 81, 83, 84, 85, 88, 92, 98, 100, 107, 111, 112, 113, 116, 117, 118, 120, 123, 125, 126, 162,167, 168, 177,178, 182

It seem to occur most offen when there is a top image and only shows the first line if it is in a diffent color and larger.

**Comment by rogrmil** [comment]
what is your screen resolution? I don't seem to have that problem. Also, please attach more images

**Comment by rogrmil** [comment]
This is what mine looks like
![screenshot from 2015-06-04 09-44-55](https://cloud.githubusercontent.com/assets/3177877/7985399/7472f264-0a9e-11e5-93b3-b70bcefaa6ec.png)

**Comment by rogrmil** [comment]
I think the newest commit fixes it. You will not have to re download anything

**Comment by aDragon** [comment]
My resolution is 1366 x 768 and it is still there after the update.
![Uploading Screenshot from 2015-06-04 18-08-10.png…]()
